In [66]:
# Looking at the Cooler condition as the target:
import pandas as pd
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier



In [102]:
from sklearn.datasets import load_iris
iris = load_iris()



In [121]:
# Load targets:
targets = pd.read_csv('./data/profile.txt',sep="\t", header= None)
targets.columns = ["Cooler cond",
              "Valve cond",
              "Internal pump leakage",
              "Hydraulic accumulator",
              "stable flag"]
targets.head()

Cooler cond  Valve cond  Internal pump leakage  Hydraulic accumulator  \
0            3         100                      0                    130   
1            3         100                      0                    130   
2            3         100                      0                    130   
3            3         100                      0                    130   
4            3         100                      0                    130   

   stable flag  
0            1  
1            1  
2            1  
3            1  
4            1

In [26]:
y = df.loc[:,"Cooler cond"]
y.shape

(2205,)

In [137]:
# Load data samples
CE = pd.read_csv('./data/CE.txt',sep="\t", header= None)
CP = pd.read_csv('./data/CP.txt',sep="\t", header= None)

# Concat the samples
samples = pd.concat([CE, CP], axis=1)
dataset = pd.concat([samples,df],axis=1)

dataset

0       1       2       3       4       5       6       7       8  \
0     47.202  47.273  47.250  47.332  47.213  47.372  47.273  47.438  46.691   
1     29.208  28.822  28.805  28.922  28.591  28.643  28.216  27.812  27.514   
2     23.554  23.521  23.527  23.008  23.042  23.052  22.658  22.952  22.908   
3     21.540  21.419  21.565  20.857  21.052  21.039  20.926  20.912  20.989   
4     20.460  20.298  20.350  19.867  19.997  19.972  19.924  19.813  19.691   
5     19.651  19.635  19.533  19.627  19.073  19.202  19.202  19.116  18.652   
6     19.339  19.415  19.040  19.003  18.996  19.033  19.055  18.887  18.881   
7     18.788  18.415  18.426  18.342  18.317  18.372  18.386  18.706  18.670   
8     18.362  18.405  18.405  18.426  18.380  18.480  18.566  18.075  18.340   
9     18.201  18.257  18.312  18.201  18.364  18.108  18.139  18.167  18.234   
10    18.184  18.195  18.268  18.485  18.398  18.444  18.280  18.525  18.236   
11    18.229  18.376  18.509  18.533  18.417  18.457  18.444  18.301  18.235   
12    17.748  17.862  17.867  17.838  17.765  17.554  17.786  17.746  17.759   
13    17.726  17.746  17.838  17.776  17.721  18.073  17.696  17.574  17.622   
14    17.561  17.763  17.821  17.771  17.704  17.648  17.838  17.784  17.763   
15    17.922  17.786  17.711  17.489  17.593  17.675  17.718  17.637  17.629   
16    17.675  17.559  17.564  17.828  17.865  17.484  17.456  17.526  17.561   
17    17.718  17.857  17.998  17.988  17.959  17.904  17.538  17.930  17.950   
18    17.727  17.764  17.440  17.416  17.392  17.404  17.496  17.396  17.506   
19    17.356  17.552  17.579  17.543  17.866  17.829  17.837  17.846  17.767   
20    17.732  17.792  17.726  17.749  17.753  17.784  17.797  17.732  17.804   
21    17.809  17.689  17.727  17.878  17.921  17.973  17.977  18.099  18.005   
22    17.753  17.679  17.922  17.957  17.950  17.919  17.957  17.922  17.680   
23    17.885  18.075  18.106  18.004  18.117  18.046  18.020  18.140  18.057   
24    17.925  18.045  18.340  18.199  18.340  18.253  18.275  18.275  18.206   
25    17.830  17.846  18.131  18.134  18.158  18.192  18.386  18.442  18.442   
26    18.341  18.339  18.591  18.605  18.372  18.350  18.570  18.352  18.292   
27    18.606  18.592  19.058  19.080  19.067  18.797  18.825  18.885  18.607   
28    18.446  18.402  18.741  18.437  18.704  18.397  18.487  18.227  18.164   
29    18.156  18.444  18.502  18.461  18.459  18.499  18.437  18.383  18.361   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
2175  46.894  46.800  46.968  46.917  46.905  47.139  47.127  47.093  47.175   
2176  46.405  46.336  46.917  46.279  46.359  46.386  46.421  46.404  46.348   
2177  46.872  47.056  47.162  47.139  47.188  47.106  47.041  47.017  46.905   
2178  46.348  46.472  46.453  46.336  46.384  46.430  46.348  46.348  46.430   
2179  46.409  46.405  46.359  46.495  46.455  46.409  46.405  46.429  46.508   
2180  46.500  46.384  46.458  46.491  46.348  46.429  46.322  46.368  46.404   
2181  46.371  46.359  46.453  46.266  46.302  46.348  46.334  46.334  46.298   
2182  46.322  46.460  46.252  46.359  46.414  46.218  46.371  46.311  46.266   
2183  46.775  46.847  46.808  46.849  46.942  46.778  46.800  46.786  46.763   
2184  46.916  46.872  47.010  46.778  46.824  46.931  46.872  46.905  46.823   
2185  46.892  46.729  46.823  46.775  46.778  46.823  46.786  46.775  46.931   
2186  46.167  46.359  46.061  46.098  46.892  46.882  46.144  46.085  46.061   
2187  46.605  46.617  46.700  46.628  46.559  46.663  46.671  46.651  46.663   
2188  46.548  46.608  46.654  46.642  46.564  46.548  46.568  46.568  46.617   
2189  46.593  46.605  46.616  46.605  46.640  46.651  46.546  46.640  46.546   
2190  46.262  46.559  46.288  46.546  46.522  46.617  47.032  47.031  46.901   
2191  46.869  46.477  46.823  46.499  46.824  47.227  46.997  46.960  46.983   
2192  45.800  45.882  45.623  45.728  45.691  45.737  45.762  45.800  45.655   
2193  46.75

In [139]:
def splitdataset(dataset): 
  
    # Seperating the target variable 
    Y = dataset.loc[:,'Cooler cond'] 
    X = dataset.values[:, 0:120] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 

X, Y, X_train, X_test, y_train, y_test = splitdataset(dataset)

print(X.shape)
print(Y.shape)
print(" ")
print(X_train.shape)
print(y_train.shape)
print(X_train)

(2205, 120)
(2205,)
 
(1543, 120)
(1543,)
[[46.725 46.724 46.749 ...  2.132  2.132  2.141]
 [46.677 46.677 46.68  ...  2.228  2.223  2.231]
 [20.661 20.715 20.715 ...  1.574  1.568  1.582]
 ...
 [20.82  20.953 20.982 ...  1.547  1.54   1.559]
 [46.453 46.323 46.453 ...  2.119  2.14   2.147]
 [46.421 46.505 46.398 ...  2.138  2.141  2.141]]


In [147]:
# DT
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X_train, y_train)

target_names = np.array([3,20,100])
tree

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [145]:
from sklearn import tree
from sklearn.tree import export_graphviz


In [153]:
# Visualize Decision Tree

# Creates dot file named tree.dot
export_graphviz(
            tree,
            out_file =  "myTreeName.dot",
            feature_names = list(samples.columns),
            class_names = target_names,
            filled = True,
            rounded = True)

TypeError: can only concatenate str (not "numpy.int64") to str