In [2]:
import pandas as pd
import pickle
import os
import nbimporter

import fill_in_blanks



In [3]:
x =2 
x

2

In [4]:
all_csv_to_dfs = []
directory = "./scada_data/30okt"

for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        full_path = os.path.join(directory, filename)
        print(full_path)
        df = pd.read_csv(os.path.join(directory, filename),sep=";")
        all_csv_to_dfs.append(df)

        continue 
    else: 
        continue

./scada_data/30okt/exporteddata_2eada060-b184-49c0-993e-c43c450b3c64.csv
./scada_data/30okt/exporteddata_e8e10168-d4c8-4600-ba27-3c2f970a4571_15_to_19.csv
./scada_data/30okt/exporteddata_47ecd0f0-6dcb-4c37-9e69-1c4d436d1ac5.csv
./scada_data/30okt/6_11.csv
./scada_data/30okt/exporteddata_f97f5d6b-949b-4b88-8e33-3cc653a6139e.csv
./scada_data/30okt/exporteddata_bcaa95fd-3366-4498-bfd3-93b20d5c0298.csv
./scada_data/30okt/exporteddata_809fc076-94c1-4e37-bc4e-8ef5119640b5.csv
./scada_data/30okt/exporteddata_51321151-ff2d-4f22-b3f1-d4e0baf71601.csv
./scada_data/30okt/exporteddata_b1e351a0-cd78-481a-a519-f221b1a6b9d7 (1).csv
./scada_data/30okt/exporteddata_f97f5d6b-949b-4b88-8e33-3cc653a6139e (1).csv
./scada_data/30okt/exporteddata_038a2254-dbe0-41c3-9610-130b914885a6.csv
./scada_data/30okt/exporteddata_af8b4654-5030-4edd-8570-6fdb403c6483.csv
./scada_data/30okt/exporteddata_5f5cbde0-077c-4ac6-843b-1db492ea6bf8.csv
./scada_data/30okt/exporteddata_fa2cb4c6-74ed-4c0c-90e3-bcfe0dfd921c.csv


In [5]:
len(all_csv_to_dfs)

14

In [6]:
for df in all_csv_to_dfs:
    print(df.TimeStamp[0])

24-10-2017 00:00:00.000
24-10-2017 00:00:00.000
24-09-2017 00:00:00.000
20-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000
24-10-2017 00:00:00.000
24-09-2017 00:00:00.000
24-09-2017 00:00:00.000


### Make sure all dataframes have the same length

In [7]:
# Show one dataframe
# Splitting dataframes from date: 25-09-2017 13:20:00

all_csv_to_dfs = fill_in_blanks.slice_df(all_csv_to_dfs)

(array([4480]),)
4480
(array([4480]),)
4480
(array([90880]),)
90880
(array([102400]),)
102400
(array([90880]),)
90880
(array([90880]),)
90880
(array([90880]),)
90880
(array([90880]),)
90880
(array([90880]),)
90880
(array([90880]),)
90880
(array([90880]),)
90880
(array([4480]),)
4480
(array([90880]),)
90880
(array([90880]),)
90880


In [8]:
import numpy as np
# Cutting away rows after date: "20-10-2019 13:20:00"
# All dataframes should now have the same shape[1].
i = 0
for dataframe in all_csv_to_dfs:

    location = np.where(dataframe["TimeStamp"].str.contains("20-10-2019 13:20:00"))
    print(location)
    split_on_index = location[0][0]
    print(split_on_index)

    # Splitting
    df1 = dataframe.iloc[:split_on_index, :]
    df2 = dataframe.iloc[split_on_index:, :]

    # Reseting index
    df1 = df1.reset_index(drop=True)
    all_csv_to_dfs[i] = df1
    i+=1

(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000
(array([2088000]),)
2088000


In [9]:
all_csv_to_dfs[0].iloc[:,0]

0          25-10-2017 13:20:00.000
1          25-10-2017 13:20:30.000
2          25-10-2017 13:21:00.000
3          25-10-2017 13:21:30.000
4          25-10-2017 13:22:00.000
5          25-10-2017 13:22:30.000
6          25-10-2017 13:23:00.000
7          25-10-2017 13:23:30.000
8          25-10-2017 13:24:00.000
9          25-10-2017 13:24:30.000
10         25-10-2017 13:25:00.000
11         25-10-2017 13:25:30.000
12         25-10-2017 13:26:00.000
13         25-10-2017 13:26:30.000
14         25-10-2017 13:27:00.000
15         25-10-2017 13:27:30.000
16         25-10-2017 13:28:00.000
17         25-10-2017 13:28:30.000
18         25-10-2017 13:29:00.000
19         25-10-2017 13:29:30.000
20         25-10-2017 13:30:00.000
21         25-10-2017 13:30:30.000
22         25-10-2017 13:31:00.000
23         25-10-2017 13:31:30.000
24         25-10-2017 13:32:00.000
25         25-10-2017 13:32:30.000
26         25-10-2017 13:33:00.000
27         25-10-2017 13:33:30.000
28         25-10-201

In [10]:
# If a csv contains more than one:

import pandas as pd
import numpy as np
import gc
# Function returns a list of dfs for each datafram
def parce_csv_with_multiple_wt(df):

  scada_dfs1 = []
  for i in range(0,25):
      if (i < 9):
          wt = ("BESS-WTG0{0}".format(i+1))
      else:
          wt = ("BESS-WTG{0}".format(i+1))

      ''' 
       Check which column names contain the string wt.
       Fro example, BESS-WT02XXXXX, is a paramenter for turbine 02
       and is filtered into a seperate dataframe:
      '''
      # Take out the TimeStamp column, since it is being filtered away:
      time_stamp_column = df.iloc[:,0]

      filtered = df[df.columns[df.columns.to_series().str.contains(wt)]]
      filtered.insert(loc=0, column='TimeStamp', value=time_stamp_column)

      # Add it to the return list
      if (filtered.shape[1] > 0):
        print("FILTERED", filtered.shape)

        scada_dfs1.append(filtered)
        print("Appended...")
  del df
  gc.collect()
    
  return scada_dfs1

In [11]:
finished_list = []
for dataframe in all_csv_to_dfs:
  more_than_one = (dataframe.shape[1] > 35)

  if (more_than_one):
    print("more_than_one", more_than_one)
    
    # Split it into more
    parced_list = parce_csv_with_multiple_wt(dataframe)
    
    for parced in parced_list:
      print("parced.shape[1]: ", parced.shape[1])
      if (parced.shape[1] == 35):
        finished_list.append(parced)
  else:
    # just add it to the list if it has all the features we need
    if (dataframe.shape[1] == 35):
      finished_list.append(dataframe)



more_than_one True
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.s

FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 35)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
FILTERED (2088000, 1)
Appended...
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.shape[1]:  1
parced.

In [12]:
print(len(finished_list))

31


In [13]:
# Make a new array with unique dataframes

def check_in_in_list(df,list1):
    boolean = "false"
    for l in list1:
        if(df.columns.equals(l.columns)):
            boolean = "true"
    return boolean
            

def unique(list1): 
  
    # intilize a null list 
    unique_list = [] 
      
    # traverse for all elements 
    for x in list1: 
        # check if exists in unique_list or not 
        if (check_in_in_list(x,unique_list) == "false"):
            unique_list.append(x) 
    return unique_list

unique_finished = unique(finished_list)


In [14]:
# The unique dataframes:

print(len(unique_finished))
# for u in unique_finished:
unique_finished[0].head()

24


TimeStamp  BESS-WTG13-WindVane (Average)  \
0  25-10-2017 13:20:00.000                            NaN   
1  25-10-2017 13:20:30.000                            NaN   
2  25-10-2017 13:21:00.000                            NaN   
3  25-10-2017 13:21:30.000                            NaN   
4  25-10-2017 13:22:00.000                            NaN   

   BESS-WTG13-WindSpeed (Average)  BESS-WTG13-RotorSpeed (Average)  \
0                             6.4                            11.63   
1                             NaN                              NaN   
2                             NaN                              NaN   
3                             4.6                            10.94   
4                             NaN                              NaN   

   BESS-WTG13-NacelleDirection (Average)  BESS-WTG13-ActivePower (Average)  \
0                                  139.0                             116.0   
1                                    NaN                               NaN   
2                                    NaN                               NaN   
3                                  138.0                              81.0   
4                                    NaN                               NaN   

   BESS-WTG13-Spinner-Temperature (Average)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   

   BESS-WTG13-Log-T-Raw-FrontBearingTemperature (Average)  \
0                                                NaN        
1                                                NaN        
2                                                NaN        
3                                                NaN        
4                                                NaN        

   BESS-WTG13-Log-T-Raw-RearBearingTemperature (Average)  \
0                                                NaN       
1                                                NaN       
2                                                NaN       
3                                                NaN       
4                                                NaN       

   BESS-WTG13-Log-T-Raw-BladeAPitchHeatSink (Average)  ...  \
0                                                NaN   ...   
1                                                NaN   ...   
2                                                NaN   ...   
3                                                NaN   ...   
4                                                NaN   ...   

   BESS-WTG13-Log-T-Raw-Rectifier1HeatSink (Average)  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

   BESS-WTG13-Log-T-Raw-Rectifier2HeatSink (Average)  \
0                                               59.0   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

   BESS-WTG13-Log-T-Raw-RectifierCabinetTemperature (Average)  \
0                                                NaN            
1                                                NaN            
2                                                NaN            
3                                                NaN            
4                                                NaN            

   BESS-WTG13-Log-T-Raw-ExcitationHeatSink (Average)  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                              

## Saving the dataframes to folder

In [15]:
path = "./DataFromBazefield/scada_data_bessaker/"
#path = '/Volumes/Uten navn/scada_data_bessaker/'
# Sorting so that we have df from 01 -> 24.
sorted_list = sorted(unique_finished, key=lambda x: x.columns[1].split("-")[1], reverse=False)


for dataframe in sorted_list:
    windturbine_id = dataframe.columns[1].split("-")[1]
    print(windturbine_id)
    
    # SAVE IT: Uncomment
    dataframe.to_csv(path + windturbine_id + ".gz", compression='gzip')

    #dataframe.to_pickle(path + windturbine_id + ".csv")


WTG02
WTG03
WTG04
WTG05
WTG06
WTG07
WTG08
WTG09
WTG10
WTG11
WTG12
WTG13
WTG14
WTG15
WTG16
WTG17
WTG18
WTG19
WTG20
WTG21
WTG22
WTG23
WTG24
WTG25
