In [10]:
# Looking at the Cooler condition as the target:
import pandas as pd
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier



In [11]:
from sklearn.datasets import load_iris
iris = load_iris()



In [12]:
# Load targets:
targets = pd.read_csv('./data/profile.txt',sep="\t", header= None)
targets.columns = ["Cooler cond",
              "Valve cond",
              "Internal pump leakage",
              "Hydraulic accumulator",
              "stable flag"]
targets.head()

Cooler cond  Valve cond  Internal pump leakage  Hydraulic accumulator  \
0            3         100                      0                    130   
1            3         100                      0                    130   
2            3         100                      0                    130   
3            3         100                      0                    130   
4            3         100                      0                    130   

   stable flag  
0            1  
1            1  
2            1  
3            1  
4            1

In [13]:
y = targets.loc[:,"Cooler cond"]
y.shape

(2205,)

In [19]:
# Load data samples
CE = pd.read_csv('./data/CE.txt',sep="\t", header= None)
CP = pd.read_csv('./data/CP.txt',sep="\t", header= None)

# Concat the samples
samples = pd.concat([CE, CP], axis=1)
dataset = pd.concat([samples,y],axis=1)
dataset.head()

0       1       2       3       4       5       6       7       8  \
0  47.202  47.273  47.250  47.332  47.213  47.372  47.273  47.438  46.691   
1  29.208  28.822  28.805  28.922  28.591  28.643  28.216  27.812  27.514   
2  23.554  23.521  23.527  23.008  23.042  23.052  22.658  22.952  22.908   
3  21.540  21.419  21.565  20.857  21.052  21.039  20.926  20.912  20.989   
4  20.460  20.298  20.350  19.867  19.997  19.972  19.924  19.813  19.691   

        9  ...     51     52     53     54     55     56     57     58     59  \
0  46.599  ...  1.470  1.458  1.452  1.443  1.449  1.428  1.401  1.402  1.383   
1  27.481  ...  1.195  1.193  1.179  1.178  1.177  1.152  1.158  1.147  1.164   
2  22.359  ...  1.102  1.099  1.099  1.118  1.112  1.116  1.108  1.085  1.103   
3  20.882  ...  1.099  1.075  1.088  1.097  1.086  1.101  1.097  1.100  1.091   
4  19.634  ...  1.093  1.085  1.087  1.082  1.105  1.101  1.097  1.100  1.106   

   Cooler cond  
0            3  
1            3  
2            3  
3            3  
4            3  

[5 rows x 121 columns]

In [139]:
def splitdataset(dataset): 
  
    # Seperating the target variable 
    Y = dataset.loc[:,'Cooler cond'] 
    X = dataset.values[:, 0:120] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 

X, Y, X_train, X_test, y_train, y_test = splitdataset(dataset)

print(X.shape)
print(Y.shape)
print(" ")
print(X_train.shape)
print(y_train.shape)
print(X_train)

(2205, 120)
(2205,)
 
(1543, 120)
(1543,)
[[46.725 46.724 46.749 ...  2.132  2.132  2.141]
 [46.677 46.677 46.68  ...  2.228  2.223  2.231]
 [20.661 20.715 20.715 ...  1.574  1.568  1.582]
 ...
 [20.82  20.953 20.982 ...  1.547  1.54   1.559]
 [46.453 46.323 46.453 ...  2.119  2.14   2.147]
 [46.421 46.505 46.398 ...  2.138  2.141  2.141]]


In [23]:
# DT
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X_train, y_train)

target_names = np.array([3,20,100])
tree

NameError: name 'X_train' is not defined

In [21]:
from sklearn import tree
from sklearn.tree import export_graphviz


In [22]:
# Visualize Decision Tree

# Creates dot file named tree.dot
export_graphviz(
            tree,
            out_file =  "myTreeName.dot",
            feature_names = list(samples.columns),
            class_names = target_names,
            filled = True,
            rounded = True)

NameError: name 'target_names' is not defined