In [1]:
# Looking at the Cooler condition as the target:
import pandas as pd
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier



## We only explore the cooler data to monitor its condition:

In [4]:
# Load data samples
CE = pd.read_csv('./Hydraulic data/CE.txt',sep="\t", header= None)
CP = pd.read_csv('./Hydraulic data/CP.txt',sep="\t", header= None)

# Concat the samples
samples = pd.concat([CE, CP], axis=1)
dataset = pd.concat([samples,y],axis=1)
dataset.head()

In [ ]:
# Concat the samples
samples = pd.concat([CE, CP], axis=1)
dataset = pd.concat([samples,y],axis=1)
dataset.head()

In [12]:
# Load targets:
targets = pd.read_csv('./Hydraulic data/profile.txt',sep="\t", header= None)
targets.columns = ["Cooler cond",
              "Valve cond",
              "Internal pump leakage",
              "Hydraulic accumulator",
              "stable flag"]
targets.head()

Cooler cond  Valve cond  Internal pump leakage  Hydraulic accumulator  \
0            3         100                      0                    130   
1            3         100                      0                    130   
2            3         100                      0                    130   
3            3         100                      0                    130   
4            3         100                      0                    130   

   stable flag  
0            1  
1            1  
2            1  
3            1  
4            1

In [13]:
y = targets.loc[:,"Cooler cond"]
y.shape

(2205,)

In [139]:
def splitdataset(dataset): 
  
    # Seperating the target variable 
    Y = dataset.loc[:,'Cooler cond'] 
    X = dataset.values[:, 0:120] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 

X, Y, X_train, X_test, y_train, y_test = splitdataset(dataset)

print(X.shape)
print(Y.shape)
print(" ")
print(X_train.shape)
print(y_train.shape)
print(X_train)

(2205, 120)
(2205,)
 
(1543, 120)
(1543,)
[[46.725 46.724 46.749 ...  2.132  2.132  2.141]
 [46.677 46.677 46.68  ...  2.228  2.223  2.231]
 [20.661 20.715 20.715 ...  1.574  1.568  1.582]
 ...
 [20.82  20.953 20.982 ...  1.547  1.54   1.559]
 [46.453 46.323 46.453 ...  2.119  2.14   2.147]
 [46.421 46.505 46.398 ...  2.138  2.141  2.141]]


In [23]:
# DT
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X_train, y_train)

target_names = np.array([3,20,100])
tree

NameError: name 'X_train' is not defined

In [21]:
from sklearn import tree
from sklearn.tree import export_graphviz


In [22]:
# Visualize Decision Tree

# Creates dot file named tree.dot
export_graphviz(
            tree,
            out_file =  "myTreeName.dot",
            feature_names = list(samples.columns),
            class_names = target_names,
            filled = True,
            rounded = True)

NameError: name 'target_names' is not defined